# Generated by Django 5.1.4 on 2024-12-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_course_student_email_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
