# Generated by Django 5.1.4 on 2024-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='is_attempted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
