# Generated by Django 5.1.4 on 2024-12-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_examregistration_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_type',
            field=models.CharField(default='Unkown', max_length=100),
        ),
    ]
